<?xml version="1.0"?>
<!-- Arm description for Jupiter2 Arm -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find jupiterobot2_arm_description)/urdf/arm_hardware.xacro"/>

  <xacro:macro name="jupiterobot2_arm" params="parent color gripper_color *origin">
    <link name="arm_base_link"/>
    <joint name="arm_base_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="arm_base_link"/>
    </joint>

    <!-- arm servo ID1 joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_base_link" name="arm1_servo">
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    </xacro:dynamixel_AX12_fixed>
    <xacro:bioloid_F3_revolute parent="arm1_servo_link" name="arm1" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${arm1_llimit}" ulimit="${arm1_ulimit}">
      <origin xyz="0 ${AX12_WIDTH/2} 0" rpy="${-M_PI/2} ${M_PI/2} ${M_PI}"/>
    </xacro:bioloid_F3_revolute>

    <!-- arm servo ID2 joint -->
    <xacro:dynamixel_AX12_fixed parent="arm1_link" name="arm2_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </xacro:dynamixel_AX12_fixed>
    <xacro:bioloid_F4_revolute parent="arm2_servo_link" name="arm2" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${arm2_llimit}" ulimit="${arm2_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F4_revolute>
    <xacro:bioloid_F10_fixed parent="arm2_link" name="arm2_F10_1" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F10_fixed parent="arm2_F10_1_link" name="arm2_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F10_fixed parent="arm2_F10_2_link" name="arm2_F10_3" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F3_fixed parent="arm2_F10_3_link" name="arm2_F3" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${M_PI} 0"/>
    </xacro:bioloid_F3_fixed>

    <!-- arm servo ID3 joint -->
    <xacro:dynamixel_AX12_fixed parent="arm2_F3_link" name="arm3_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </xacro:dynamixel_AX12_fixed>
    <xacro:bioloid_F4_revolute parent="arm3_servo_link" name="arm3" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${arm3_llimit}" ulimit="${arm3_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F4_revolute>
    <xacro:bioloid_F10_fixed parent="arm3_link" name="arm3_F10_1" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F10_fixed parent="arm3_F10_1_link" name="arm3_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F10_fixed parent="arm3_F10_2_link" name="arm3_F10_3" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F3_fixed parent="arm3_F10_3_link" name="arm3_F3" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${M_PI} 0"/>
    </xacro:bioloid_F3_fixed>

    <!-- arm servo ID4 joint -->
    <xacro:dynamixel_AX12_fixed parent="arm3_F3_link" name="arm4_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </xacro:dynamixel_AX12_fixed>
    <xacro:bioloid_F2_revolute parent="arm4_servo_link" name="arm4" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${arm4_llimit}" ulimit="${arm4_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F2_revolute>

    <!-- fake gripper_link joint gives us a free servo!
         this makes us 5DOF and saves you $44.90
         that's a lot of coin! -->
    <link name="gripper_link"/>
    <joint name="gripper_link_joint" type="revolute">
      <origin xyz="0 0 0.112" rpy="0 -1.57 0"/>
      <parent link="arm4_link"/>
      <child link="gripper_link"/>
      <limit effort="30" velocity="1" lower="-3.14" upper="3.14"/>
      <axis xyz="1 0 0"/>
    </joint>

    <!-- gripper - Load Jupiter2 gripper -->
    <xacro:include filename="$(find jupiterobot2_arm_description)/urdf/jupiterobot2_gripper.xacro"/>

    <!-- Load -->
    <xacro:include filename="$(find jupiterobot2_arm_description)/urdf/jupiterobot2_arm_gazebo.xacro"/>

  </xacro:macro>

</robot>
