joints: ['arm1_joint', 'arm2_joint', 'arm3_joint', 'arm4_joint', 'gripper_joint', 'head_joint']

arm1_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm1_joint
    joint_speed: 0.8
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

arm2_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm2_joint
    joint_speed: 0.8
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023

arm3_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm3_joint
    joint_speed: 0.8
    motor:
        id: 3
        init: 512
        min: 0
        max: 1023

arm4_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm4_joint
    joint_speed: 0.8
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023

gripper_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: gripper_joint
    joint_speed: 0.8
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023

head_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_joint
    joint_speed: 0.8
    motor:
        id: 6
        init: 512
        min: 0
        max: 1023
