joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm1_joint
    - arm2_joint
    - arm3_joint
    - arm4_joint
  gains:
    arm1_joint: {p: 1000, i: 5, d: 10, i_clamp: 1}
    arm2_joint: {p: 1000, i: 5, d: 10, i_clamp: 1}
    arm3_joint: {p: 1000, i: 5, d: 10, i_clamp: 1}
    arm4_joint: {p: 1000, i: 5, d: 10, i_clamp: 1}

gripper_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_joint
  gains:
    gripper_joint: {p: 1000, i: 5, d: 10, i_clamp: 1}

head_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_joint
  gains:
    head_joint: {p: 1000, i: 5, d: 10, i_clamp: 1}
