<?xml version="1.0"?>
<robot name="sensor_camera_top" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Xacro properties -->
    <xacro:property name="cam_px" value="0.000"/>
    <xacro:property name="cam_py" value="-0.009"/>
    <xacro:property name="cam_pz" value="0.000"/>
    <xacro:property name="cam_depth_offset" value="0.001"/>
    <!-- camera_top properties -->
    <xacro:macro name="sensor_camera_top" params="parent">
        <joint name="camera_joint" type="fixed">
            <origin xyz="-0.0125 0 -0.0215" rpy="0 ${M_PI} 0"/>
            <parent link="${parent}"/>
            <child link="camera_link"/>
        </joint>
        <link name="camera_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://jupiterobot2_head_description/meshes/camera.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="DarkGrey"/>
            </visual>
            <collision>
                <origin xyz="-0.0125 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.025 0.109 0.025"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="-0.0125 0 0" rpy="0 0 0" />
                <mass value="0.06" />
                <inertia ixx="6.253e-05" ixy="0.0" ixz="0.0"
                         iyy="6.25e-06" iyz="0.0"
                         izz="6.253e-05" />
            </inertial>
        </link>
        <gazebo reference="camera_link">
            <material>Gazebo/DarkGrey</material>
            <selfCollide>true</selfCollide>
            <gravity>true</gravity>
        </gazebo>

        <joint name="camera_color_joint" type="fixed">
            <origin xyz="${cam_px} ${cam_py} ${cam_pz}" rpy="0 0 0"/>
            <parent link="camera_link"/>
            <child link="camera_color_frame"/>
        </joint>
        <link name="camera_color_frame"/>

        <joint name="camera_color_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}"/>
            <parent link="camera_color_frame"/>
            <child link="camera_color_optical_frame"/>
        </joint>
        <link name="camera_color_optical_frame"/>

        <joint name="camera_depth_joint" type="fixed">
            <origin xyz="${cam_px} ${cam_py + cam_depth_offset} ${cam_pz}" rpy="0 0 0"/>
            <parent link="camera_link"/>
            <child link="camera_depth_frame"/>
        </joint>
        <link name="camera_depth_frame"/>

        <joint name="camera_depth_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}"/>
            <parent link="camera_depth_frame"/>
            <child link="camera_depth_optical_frame"/>
        </joint>
        <link name="camera_depth_optical_frame"/>
    </xacro:macro>

</robot>
