controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - arm4_joint
      - gripper_link_joint
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_joint
  - name: fake_head_group_controller
    type: $(arg fake_execution_type)
    joints:
      - head_joint
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: up
  - group: gripper_group
    pose: rest
  - group: head_group
    pose: rest