# 0 nose 鼻子
# 1 left_eye_inner 左眼内角
# 2 left_eye 左眼
# 3 left_eye_outer 左眼外角
# 4 right_eye_inner 右眼内角
# 5 right_eye 右眼
# 6 right_eye_outer 右眼外角
# 7 left_ear 左耳
# 8 right_ear 右耳
# 9 mouth_left 左嘴
# 10 mouth_right 右嘴
# 11 left_shoulder 左肩
# 12 right_shoulder 右肩
# 13 left_elbow 左肘
# 14 right_elbow 右肘
# 15 left_wrist 左手腕
# 16 right_wrist 右手腕
# 17 left_pinky 左小指
# 18 right_pinky 右小指
# 19 left_index 左食指
# 20 right_index 右食指
# 21 left_thumb 左拇指
# 22 right_thumb 右拇指
# 23 left_hip 左臀
# 24 right_hip 右臀
# 25 left_knee 左膝
# 26 right_knee 右膝
# 27 left_ankle 左脚踝
# 28 right_ankle 右脚踝
# 29 left_heel 左脚底
# 30 right_heel 右脚底
# 31 left_foot_index 左脚指尖
# 32 right_foot_index 右脚指尖
Header times
Joint nose
Joint left_eye_inner
Joint left_eye
Joint left_eye_outer
Joint right_eye_inner
Joint right_eye
Joint right_eye_outer
Joint left_ear
Joint right_ear
Joint mouth_left
Joint mouth_right
Joint left_shoulder
Joint right_shoulder
Joint left_elbow
Joint right_elbow
Joint left_wrist
Joint right_wrist
Joint left_pinky
Joint right_pinky
Joint left_index
Joint right_index
Joint left_thumb
Joint right_thumb
Joint left_hip
Joint right_hip
Joint left_knee
Joint right_knee
Joint left_ankle
Joint right_ankle
Joint left_heel
Joint right_heel
Joint left_foot_index
Joint right_foot_index